name: BlockTower
version: @version@
main: gamio.blocks.blocktower.BlockTower
commands:
  blocktower:
    usage:  /<command>
    permission: blocktower.command


permissions:
  blocktower.command:
    default: op